export const PROCEDIMENTOS_ESTETICOS: string[] = [
  "Toxina botulínica",
  "Preenchimento com ácido hialurônico",
  "Harmonização facial",
  "Bioestimulador de colágeno",
  "Hidroxiapatita de cálcio",
  "Skinbooster",
  "PRP (plasma rico em plaquetas)",
  "Mesoterapia",
  "Intradermoterapia",
  "Lipo enzimática",
  "Fios de sustentação (PDO)",
  "Rinomodelação",
  "Preenchimento labial",
  "Microagulhamento",
  "Microagulhamento com radiofrequência",
  "Drug delivery",
  "Peeling químico",
  "Peeling de diamante",
  "Peeling de cristal",
  "Microdermoabrasão",
  "Limpeza de pele",
  "Luz intensa pulsada",
  "Fotorejuvenescimento",
  "Ultrassom microfocado (HIFU)",
  "Radiofrequência facial",
  "Criofrequência facial",
  "Jato de plasma",
  "LED terapia",
  "Laser fracionado",
  "Laser de picossegundos",
  "Lavieen",
  "Lifting facial não cirúrgico",
  "Hidratação facial profunda",
  "Depilação a laser",
  "Criolipólise",
  "Radiofrequência corporal",
  "Drenagem linfática",
  "Massagem modeladora",
  "Carboxiterapia",
  "Lipocavitação",
  "Ultrassom focado corporal",
  "Endermologia (LPG)",
  "Vacuoterapia",
  "Pressoterapia",
  "Subcision para celulite",
  "Tratamento para estrias",
  "Bandagem modeladora",
  "Eletroestimulação muscular",
  "Hidrolipoclasia",
  "Argiloterapia",
];
